# FROM python:3.10.12

# WORKDIR /FastAPI

# COPY main.py requirements.txt ./

# RUN pip install -r requirements.txt

# EXPOSE 8000

# CMD ["uvicorn", "main:app", "--port", "8000" ,"--reload"]

FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

WORKDIR /FastAPI

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

EXPOSE 8075

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8075"]
